version: '3'

services:
  db:
    image: postgres:13.3
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: octo_admin
      POSTGRES_PASSWORD: password
    ports:
      - ${DATABASE_PORT:-5432}:5432
  spy:
    image: octo-spy:latest
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: octo_db
      DATABASE_USER: octo
      DATABASE_PASSWORD: password
      APPLICATION_ENVIRONMENT: ${APPLICATION_ENVIRONMENT:-Development}
      APPLICATION_CLIENT: ${APPLICATION_CLIENT:-Internal}
    ports:
      - ${APPLICATION_PORT:-8080}:8080
    depends_on:
      - db
