GRANT CONNECT ON DATABASE octo_db TO octo;
GRANT USAGE ON SCHEMA public TO octo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO octo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO octo;
